### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ericfrank** [ericfrank/codenames#3]
- Dark mode
- Team color chooser
- See all card colors when game ends

**Comment by hoffman-stripe** [comment]
Update the codemaster view to show cards that have been chosen.

**Comment by hoffman-stripe** [comment]
Turn timer for codemasters.

**Comment by ericfrank** [comment]
Dark mode and "See all card colors when game ends" are shipped! https://codenames.ericfrank.com

@hoffman-stripe I moved your two comments into separate issues: https://github.com/ericfrank/codenames/issues
